# Generated by Django 3.2 on 2022-07-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('date_booked', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
