# Generated by Django 3.2 on 2022-07-25 09:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_reservation_limited_integer_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='limited_integer_Field',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='seats',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
